#tomacat相关配置
server:
  port: 9002
  tomcat:
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 50 # Minimum amount of worker threads
#应用基本配置
spring:
  application:
    name: fisher-back-service

  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/baidu?useUnicode=true&characterEncoding=UTF8&useSSL=false&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    hikari:
      minimum-idle: 0

  #  redis 配置
  redis:
    host: 112.74.190.171
    port: 6379
    password: ksdtest217
    timeout: 3000
    database: 5
    pool:
      minIdle: 0
      maxIdle: 8
      maxWait: -1
      maxActive: 8

#mybatis-plus相关配置
mybatis-plus:
  mapper-locations: classpath:com/fun/crawl/mapping/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.fun.crawl.model
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_EMPTY
      #驼峰下划线转换
      table-underline: true
      #mp2.3+ 全局表前缀 mp_
      #table-prefix: mp_
      #刷新mapper 调试神器
      #refresh-mapper: true
      #数据库大写下划线转换
      #alipay-mode: true
      # Sequence序列接口实现类配置
      #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 1
      logic-not-delete-value: 0
      #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
      #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.mybatisplus.core.handlers.MetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: false
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'



ignore:
  urls:
  - /**/*.css
  - /auth/**
  - /actuator/**
  - /admin/user/**
  - /admin/resource/**
  - /admin/role/**
  - /pan/**
  - /swagger-ui.html
  - /swagger-resources/**
  - /v2/api-docs
  - /webjars/**

login:
  mobile:
    url: /login/mobile
    parameter: mobile
    codeParameter: smsCode
    httpMethod: POST

jwt:
  tokenHeader: Authorization
  tokenPrefix: Bearer
  secret: crawl
  expiration: 604800
  rememberExpiration: 604800
